// lib/dummyData.js

// ---------------- USERS ----------------
export const users = [
  {
    id: 1,
    name: "Admin User",
    phone: "01700000001",
    email: "admin@example.com",
    role: "admin",
    photo: "admin.jpg",
    created_at: "2024-01-01",
  },
  {
    id: 2,
    name: "Officer User",
    phone: "01700000002",
    email: "officer@example.com",
    role: "officer",
    photo: "officer.jpg",
    created_at: "2024-01-02",
  },
  {
    id: 3,
    name: "Researcher One",
    phone: "01700000003",
    email: "researcher1@example.com",
    role: "researcher",
    photo: "researcher1.jpg",
    created_at: "2024-01-03",
  },
  {
    id: 4,
    name: "Reviewer One",
    phone: "01700000004",
    email: "reviewer1@example.com",
    role: "reviewer",
    photo: "reviewer1.jpg",
    created_at: "2024-01-04",
  },
  {
    id: 5,
    name: "Researcher Two",
    phone: "01700000005",
    email: "researcher2@example.com",
    role: "researcher",
    photo: "researcher2.jpg",
    created_at: "2024-01-05",
  },
  {
    id: 6,
    name: "Researcher Three",
    phone: "01700000006",
    email: "researcher3@example.com",
    role: "researcher",
    photo: "researcher3.jpg",
    created_at: "2024-01-06",
  },
  {
    id: 7,
    name: "Reviewer Two",
    phone: "01700000007",
    email: "reviewer2@example.com",
    role: "reviewer",
    photo: "reviewer2.jpg",
    created_at: "2024-01-07",
  },
];

// ---------------- PROJECTS ----------------
export const projects = [
  {
    id: 1,
    code_no: "PRJ-2024-001",
    title: "AI-based Disease Detection System",
    researcher: {
      id: 1,
      name: "Researcher One",
      email: "researcher1@example.com",
      designation: "Associate Professor",
      faculty: "Faculty of Science",
      department: "Computer Science",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 500000,
    allocated_budget: 400000,
    first_allocation_amount: 200000,
    final_report_submission_due_date: "2025-06-30",
    status: "Under Review",
    submission_date: "2024-06-15",
  },
  {
    id: 2,
    code_no: "PRJ-2024-002",
    title: "Sustainable Water Purification",
    researcher: {
      id: 1,
      name: "Researcher One",
      email: "researcher1@example.com",
      designation: "Associate Professor",
      faculty: "Faculty of Science",
      department: "Computer Science",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 300000,
    allocated_budget: 0,
    status: "Proposal Submitted",
    submission_date: "2024-06-20",
  },
  {
    id: 3,
    code_no: "PRJ-2024-003",
    title: "Quantum Computing Algorithms",
    researcher: {
      id: 2,
      name: "Researcher Two",
      email: "researcher2@example.com",
      designation: "Assistant Professor",
      faculty: "Faculty of Science",
      department: "Physics",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 700000,
    allocated_budget: 500000,
    status: "Approved / Ongoing",
    submission_date: "2024-05-12",
  },
  {
    id: 4,
    code_no: "PRJ-2024-004",
    title: "Smart Agriculture using IoT",
    researcher: {
      id: 3,
      name: "Researcher Three",
      email: "researcher3@example.com",
      designation: "Lecturer",
      faculty: "Faculty of Engineering",
      department: "Civil Engineering",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 450000,
    allocated_budget: 300000,
    status: "Under Review",
    submission_date: "2024-06-05",
  },
  {
    id: 5,
    code_no: "PRJ-2024-005",
    title: "Blockchain for Supply Chain",
    researcher: {
      id: 2,
      name: "Researcher Two",
      email: "researcher2@example.com",
      designation: "Assistant Professor",
      faculty: "Faculty of Science",
      department: "Physics",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 600000,
    allocated_budget: 0,
    status: "Proposal Submitted",
    submission_date: "2024-07-01",
  },
  {
    id: 6,
    code_no: "PRJ-2024-006",
    title: "Renewable Energy Storage Solutions",
    researcher: {
      id: 3,
      name: "Researcher Three",
      email: "researcher3@example.com",
      designation: "Lecturer",
      faculty: "Faculty of Engineering",
      department: "Civil Engineering",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 800000,
    allocated_budget: 650000,
    status: "Approved / Ongoing",
    submission_date: "2024-04-25",
  },
  {
    id: 7,
    code_no: "PRJ-2024-007",
    title: "AI Tutor for Personalized Learning",
    researcher: {
      id: 1,
      name: "Researcher One",
      email: "researcher1@example.com",
      designation: "Associate Professor",
      faculty: "Faculty of Science",
      department: "Computer Science",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 350000,
    allocated_budget: 0,
    status: "Proposal Submitted",
    submission_date: "2024-06-28",
  },
  {
    id: 8,
    code_no: "PRJ-2024-008",
    title: "Cybersecurity Threat Detection",
    researcher: {
      id: 2,
      name: "Researcher Two",
      email: "researcher2@example.com",
      designation: "Assistant Professor",
      faculty: "Faculty of Science",
      department: "Physics",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 400000,
    allocated_budget: 0,
    status: "Rejected",
    submission_date: "2024-07-05",
  },
  {
    id: 9,
    code_no: "PRJ-2024-009",
    title: "Climate Change Impact on Agriculture",
    researcher: {
      id: 3,
      name: "Researcher Three",
      email: "researcher3@example.com",
      designation: "Lecturer",
      faculty: "Faculty of Engineering",
      department: "Civil Engineering",
    },
    fiscal_year: "2023-2024",
    proposed_budget: 500000,
    allocated_budget: 250000,
    status: "Completed",
    submission_date: "2024-06-10",
  },
];

// ---------------- PROJECT REPORTS ----------------
// lib/dummy.js

export const reviewers = [
  {
    id: 1,
    name: "Reviewer One",
    designation: "Professor",
    department: "Computer Science",
    university: "University of Barishal",
    phone: "01700000004",
    email: "reviewer1@example.com",
    photo: "reviewer1.jpg",
  },
  {
    id: 2,
    name: "Reviewer Two",
    designation: "Associate Professor",
    department: "Physics",
    university: "Dhaka University",
    phone: "01700000005",
    email: "reviewer2@example.com",
    photo: "reviewer2.jpg",
  },
];

export const projectReports = [
  {
    id: 1,
    project_id: 1,
    type: "proposal",
    name: "AI_proposal.pdf",
    url: "/uploads/reports/AI_proposal.pdf",
    uploaded_by: "Researcher One",
    uploaded_at: "2024-06-15",
  },
  {
    id: 2,
    project_id: 2,
    type: "proposal",
    name: "WaterPurification_proposal.pdf",
    url: "/uploads/reports/WaterPurification_proposal.pdf",
    uploaded_by: "Researcher One",
    uploaded_at: "2024-06-20",
  },
  {
    id: 3,
    project_id: 3,
    type: "final",
    name: "Quantum_final.pdf",
    url: "/uploads/reports/Quantum_final.pdf",
    uploaded_by: "Researcher Two",
    uploaded_at: "2025-01-10",
  },
];

export const projectReviews = [
  {
    id: 1,
    project_id: 1,
    reviewer_id: 1,
    reviewer_name: "Reviewer One",
    review_type: "Proposal Review",
    assigned_by: "Officer User",
    assigned_at: "2024-06-20",
    due_date: "2024-07-15",
    submitted_at: "2024-07-10",
    review_comments: "Excellent proposal with minor improvements required.",
    total_marks: 85,
    marks_breakdown: {
      innovation: 20,
      feasibility: 18,
      budget: 15,
      impact: 17,
      clarity: 15,
    },
    attachment: "/uploads/reviews/review1.pdf",
    status: "submitted",
  },
  {
    id: 2,
    project_id: 3,
    reviewer_id: 2,
    reviewer_name: "Reviewer Two",
    review_type: "Final Report Review",
    assigned_by: "Officer User",
    assigned_at: "2025-01-12",
    due_date: "2025-02-01",
    submitted_at: "2025-01-28",
    review_comments: "Great results, very impactful research.",
    total_marks: 92,
    marks_breakdown: {
      innovation: 19,
      feasibility: 19,
      budget: 18,
      impact: 20,
      clarity: 16,
    },
    attachment: "/uploads/reviews/review2.pdf",
    status: "submitted",
  },
];


// ---------------- PROJECT REVIEWS ----------------


// ---------------- PAYMENTS ----------------
export const researcherPayments = [
  {
    id: 1,
    researcher: { id: 1, name: "Researcher One", email: "researcher1@example.com" },
    project: { id: 1, code_no: "PRJ-2024-001", title: "AI-based Disease Detection System" },
    amount: 200000,
    payment_date: "2024-08-01",
    note: "First installment released",
    slot: 1,
  },
  {
    id: 2,
    researcher: { id: 2, name: "Researcher Two", email: "researcher2@example.com" },
    project: { id: 3, code_no: "PRJ-2024-003", title: "Quantum Computing Algorithms" },
    amount: 250000,
    payment_date: "2024-09-01",
    note: "First installment",
    slot: 1,
  },
];

export const reviewerPayments = [
  {
    id: 1,
    reviewer: { id: 1, name: "Reviewer One", email: "reviewer1@example.com" },
    project: { id: 1, code_no: "PRJ-2024-001", title: "AI-based Disease Detection System" },
    payment_type: "proposal_review",
    amount: 5000,
    payment_date: "2024-07-20",
  },
  {
    id: 2,
    reviewer: { id: 2, name: "Reviewer Two", email: "reviewer2@example.com" },
    project: { id: 4, code_no: "PRJ-2024-004", title: "Smart Agriculture using IoT" },
    payment_type: "final_report_review",
    amount: 7000,
    payment_date: "2024-07-25",
  },
];

// ---------------- CIRCULARS ----------------
export const circulars = [
  {
    id: 1,
    title: "Call for Research Proposals 2024",
    notice_code: "NOTICE-2024-001",
    type: "proposal",
    description: "We invite all researchers to submit their proposals for the fiscal year 2024-2025.",
    attachment: "/uploads/notices/notice1.pdf",
    published_date: "2024-05-01",
  },
  {
    id: 2,
    title: "Reminder: Proposal Submission Deadline",
    notice_code: "NOTICE-2024-002",
    type: "reminder",
    description: "Deadline for submission is June 15, 2024. Late submissions will not be considered.",
    attachment: "/uploads/notices/notice2.pdf",
    published_date: "2024-06-01",
  },
  {
    id: 3,
    title: "Updated Format for Reports",
    notice_code: "NOTICE-2024-003",
    type: "format_document",
    description: "Please use the updated template for submitting reports.",
    attachment: "/uploads/notices/notice3.pdf",
    published_date: "2024-06-10",
  },
];

// ---------------- APP SETTINGS ----------------
export const appSettings = [
  { key: "proposal_submission_due_date", value: "2024-06-15" },
  { key: "max_active_projects_per_researcher", value: "2" },
];
export const fiscalYears = [
  {
    id: 1,
    year_label: "2023-2024",
    is_active: true,
  },
  {
    id: 2,
    year_label: "2024-2025",
    is_active: false,
  },
  {
    id: 3,
    year_label: "2025-2026",
    is_active: false,
  },
];
